### PR TITLE
Merge branch 'chakracore-master' of https://github.com/nodejs/node-chakracore into chakra-uwp

### PR DESCRIPTION
**Pull request by munyirik**

### CODE REVIEW

**Comment by munyirik** [comment]
@kunalspathak you can now see the resolved conflicts in commit 6da8f8c

**Comment by munyirik** [comment]
@kunalspathak test results are below. Are the failures expected?
[nodech_test_results.txt](https://github.com/ms-iot/node/files/445811/nodech_test_results.txt)

**Comment by kunalspathak** [comment]
Changes looks good to me. So far there are approx. 20 failures that are expected, but in your case there are 41 failures, which seems something is wrong.

**Comment by munyirik** [comment]
I hadn't set git bin in Path which is why I got some of the failures. The number of unexpected failures is 13. I believe they are unrelated to this merge. Will investigate separately. For now merging this...

**Pull request merged**
