### PR TITLE
Merge branch 'chakracore-master' of https://github.com/nodejs/node-chakracore into chakra-uwp

### PR DESCRIPTION
**Pull request by munyirik**

### CODE REVIEW

**Comment by munyirik** [comment]
@kunalspathak could you please CR. Only one minor conflict that needed to be resolved. Otherwise it works.

**Comment by munyirik** [comment]
This has some issue I need to fix first. Closing for now.

**Comment by kunalspathak** [comment]
Seems to be just a merge. LGTM if test passes. Let me know if you want me to review merge conflict.

**Comment by munyirik** [comment]
The conflict was because the line below was added.
https://github.com/ms-iot/node/blob/chakra-uwp/lib/fs.js#L1579

**Comment by kunalspathak** [comment]
👍

**Pull request merged**
